version: "3.7"

services:

  webapp:
    container_name: climbers_web
    tty: true
    build:
      context: .
    # restart: on-failure:1
    ports:
      - "8000:8000"
    volumes:
      - ./climbersproject:/climbersproject
    command: |
      sh -c
      "coverage run manage.py test && coverage report"
      # "python manage.py wait_for_db
      #  python manage.py makemigrations &&
      #  python manage.py migrate &&
      #  python manage.py runserver 0:8000"

    environment:
      - DEBUG=1
    depends_on:
      - db

  db:
      container_name: climbers_db
      image: "postgres:11"
      ports:
        - '5432:5432'
      environment:
        - POSTGRES_DB=climbers_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgrespassword
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
